routes/web.php
<?php
Route::get('/', function () {
    return redirect('/home');
});

// Auth::routes();

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');
/*$this->get('oauth2google', 'Auth\Oauth2Controller@oauth2google')->name('oauth2google');
$this->get('googlecallback', 'Auth\Oauth2Controller@googlecallback')->name('googlecallback');
$this->get('oauth2facebook', 'Auth\Oauth2Controller@oauth2facebook')->name('oauth2facebook');
$this->get('facebookcallback', 'Auth\Oauth2Controller@facebookcallback')->name('facebookcallback');
$this->get('oauth2github', 'Auth\Oauth2Controller@oauth2github')->name('oauth2github');
$this->get('githubcallback', 'Auth\Oauth2Controller@githubcallback')->name('githubcallback');*/

// Registration Routes...
/*$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');*/

// Password Reset Routes...
/*$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('auth.password.email');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');*/


Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('tests', 'TestsController');
    Route::resource('roles', 'RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'UsersController');
    Route::post('users_mass_destroy', ['uses' => 'UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'UserActionsController');
    Route::resource('topics', 'TopicsController');
    Route::post('topics_mass_destroy', ['uses' => 'TopicsController@massDestroy', 'as' => 'topics.mass_destroy']);
    Route::resource('questions', 'QuestionsController');
    Route::post('questions_mass_destroy', ['uses' => 'QuestionsController@massDestroy', 'as' => 'questions.mass_destroy']);
    Route::resource('questions_options', 'QuestionsOptionsController');
    Route::post('questions_options_mass_destroy', ['uses' => 'QuestionsOptionsController@massDestroy', 'as' => 'questions_options.mass_destroy']);
    Route::resource('results', 'ResultsController');
    Route::post('results_mass_destroy', ['uses' => 'ResultsController@massDestroy', 'as' => 'results.mass_destroy']);

    //question level
    Route::resource('questionLevel', 'QuestionLevelController');

    //question level details
    Route::resource('questionLevelDetail', 'QuestionLevelDetailController');

    //Manage Package category
    Route::resource('packageCategory', 'PackageCategoryController');
    Route::post('categories_mass_destroy', ['uses' => 'PackageCategoryController@massDestroy', 'as' => 'packageCategory.mass_destroy']);

    //Manage Package
    Route::resource('packages', 'PackageController');

    //Manage Puzzles
    Route::resource('stages', 'StageController');

    //Manage Level
    Route::resource('levels', 'LevelController');

    //patterns
    Route::resource('patterns', 'PatternController');

    //Puzzles
    Route::resource('puzzles', 'PuzzleController');
    Route::post('load-pattern-schema','PatternSchemaController@patternSchema')->name('pattern-schema');
    Route::post('stage-wise-level','ManageDropDownController@levelListDependOnStage')->name('stage-wise-level');

    //Manage User
    Route::resource('app-users','AppUsersController');
    Route::get('push-notification','PushNotificationController@push')->name('push');
    Route::post('send-push','PushNotificationController@sendPush')->name('push.send');

    //settings
    Route::resource('pointSettings','PointSettingController');
});

app/QuestionLevelDetail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class QuestionLevelDetail extends Model
{
    protected $fillable = ['question_level_id','section_a_no_of_question','section_a_no_of_point','section_b_no_of_question','section_b_no_of_point','section_c_no_of_question','section_c_no_of_point'];

    public function level()
    {
        return $this->belongsTo(QuestionLevel::class,'question_level_id','id');
    }
}

app/Http/Controllers/QuestionLevelDetailController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\QuestionLevelDetailRequest;
use App\QuestionLevel;
use App\QuestionLevelDetail;
use Illuminate\Http\Request;

class QuestionLevelDetailController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $levelDetails = QuestionLevelDetail::with('level')->orderBy('id','desc')->get();
        return view('question_level_details.index', compact('levelDetails'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $levels = QuestionLevel::whereDoesntHave('detail')->get()->pluck('title', 'id')->prepend('Please select', '');
        return view('question_level_details.create',compact('levels'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(QuestionLevelDetailRequest $request)
    {
        QuestionLevelDetail::create($request->all());
        return redirect()->route('questionLevelDetail.index')->with('message', 'Saved successfully!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\QuestionLevelDetail  $questionLevelDetail
     * @return \Illuminate\Http\Response
     */
    public function show(QuestionLevelDetail $questionLevelDetail)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\QuestionLevelDetail  $questionLevelDetail
     * @return \Illuminate\Http\Response
     */
    public function edit(QuestionLevelDetail $questionLevelDetail)
    {
        $levels = QuestionLevel::get()->pluck('title', 'id')->prepend('Please select', '');
        return view('question_level_details.edit',compact('levels','questionLevelDetail'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\QuestionLevelDetail  $questionLevelDetail
     * @return \Illuminate\Http\Response
     */
    public function update(QuestionLevelDetailRequest $request, QuestionLevelDetail $questionLevelDetail)
    {
        $questionLevelDetail->update($request->all());
        return redirect()->route('questionLevelDetail.index')->with('message', 'Saved successfully!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\QuestionLevelDetail  $questionLevelDetail
     * @return \Illuminate\Http\Response
     */
    public function destroy(QuestionLevelDetail $questionLevelDetail)
    {
        //
    }
}

resources/views/question_level_details/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.questionLevel.details')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['questionLevelDetail.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('question_level_id', 'Question Level*', ['class' => 'control-label']) !!}
                    {!! Form::select('question_level_id', $levels, old('question_level_id'), ['class' => 'form-control']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('question_level_id'))
                        <p class="help-block">
                            {{ $errors->first('question_level_id') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6 form-group">
                    {!! Form::label('section_a_no_of_question', 'No Of Question Of Section-A*', ['class' => 'control-label']) !!}
                    {!! Form::number('section_a_no_of_question', old('section_a_no_of_question'), ['class' => 'form-control', 'placeholder' => 'Enter Section-A Question Quantity']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('section_a_no_of_question'))
                        <p class="help-block">
                            {{ $errors->first('section_a_no_of_question') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('section_a_no_of_point', 'Total Point Of Section-A*', ['class' => 'control-label']) !!}
                    {!! Form::number('section_a_no_of_point', old('section_a_no_of_point'), ['class' => 'form-control', 'placeholder' => 'Enter Section-A Point']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('section_a_no_of_point'))
                        <p class="help-block">
                            {{ $errors->first('section_a_no_of_point') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('section_b_no_of_question', 'No Of Question Of Section-B*', ['class' => 'control-label']) !!}
                    {!! Form::number('section_b_no_of_question', old('section_b_no_of_question'), ['class' => 'form-control', 'placeholder' => 'Enter Section-B Question Quantity']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('section_b_no_of_question'))
                        <p class="help-block">
                            {{ $errors->first('section_b_no_of_question') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('section_b_no_of_point', 'Total Point Of Section-B*', ['class' => 'control-label']) !!}
                    {!! Form::number('section_b_no_of_point', old('section_b_no_of_point'), ['class' => 'form-control', 'placeholder' => 'Enter Section-B Point']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('section_b_no_of_point'))
                        <p class="help-block">
                            {{ $errors->first('section_b_no_of_point') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('section_c_no_of_question', 'No Of Question Of Section-C*', ['class' => 'control-label']) !!}
                    {!! Form::number('section_c_no_of_question', old('section_c_no_of_question'), ['class' => 'form-control', 'placeholder' => 'Enter Section-C Question Quantity']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('section_c_no_of_question'))
                        <p class="help-block">
                            {{ $errors->first('section_c_no_of_question') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('section_c_no_of_point', 'Total Point Of Section-C*', ['class' => 'control-label']) !!}
                    {!! Form::number('section_c_no_of_point', old('section_c_no_of_point'), ['class' => 'form-control', 'placeholder' => 'Enter Section-C Point']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('section_c_no_of_point'))
                        <p class="help-block">
                            {{ $errors->first('section_c_no_of_point') }}
                        </p>
                    @endif
                </div>
            </div>
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/question_level_details/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.questionLevel.details')</h3>
    
    {!! Form::model($questionLevelDetail, ['method' => 'PUT', 'route' => ['questionLevelDetail.update', $questionLevelDetail->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('question_level_id', 'Question Level*', ['class' => 'control-label']) !!}
                    {!! Form::select('question_level_id', $levels, old('question_level_id'), ['class' => 'form-control','disabled '=>true]) !!}
                    {!! Form::hidden('question_level_id', $questionLevelDetail->question_level_id, ['class' => 'form-control', 'placeholder' => 'Enter Section-A Question Quantity']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('question_level_id'))
                        <p class="help-block">
                            {{ $errors->first('question_level_id') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6 form-group">
                    {!! Form::label('section_a_no_of_question', 'No Of Question Of Section-A*', ['class' => 'control-label']) !!}
                    {!! Form::number('section_a_no_of_question', old('section_a_no_of_question'), ['class' => 'form-control', 'placeholder' => 'Enter Section-A Question Quantity']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('section_a_no_of_question'))
                        <p class="help-block">
                            {{ $errors->first('section_a_no_of_question') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('section_a_no_of_point', 'Total Point Of Section-A*', ['class' => 'control-label']) !!}
                    {!! Form::number('section_a_no_of_point', old('section_a_no_of_point'), ['class' => 'form-control', 'placeholder' => 'Enter Section-A Point']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('section_a_no_of_point'))
                        <p class="help-block">
                            {{ $errors->first('section_a_no_of_point') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('section_b_no_of_question', 'No Of Question Of Section-B*', ['class' => 'control-label']) !!}
                    {!! Form::number('section_b_no_of_question', old('section_b_no_of_question'), ['class' => 'form-control', 'placeholder' => 'Enter Section-B Question Quantity']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('section_b_no_of_question'))
                        <p class="help-block">
                            {{ $errors->first('section_b_no_of_question') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('section_b_no_of_point', 'Total Point Of Section-B*', ['class' => 'control-label']) !!}
                    {!! Form::number('section_b_no_of_point', old('section_b_no_of_point'), ['class' => 'form-control', 'placeholder' => 'Enter Section-B Point']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('section_b_no_of_point'))
                        <p class="help-block">
                            {{ $errors->first('section_b_no_of_point') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('section_c_no_of_question', 'No Of Question Of Section-C*', ['class' => 'control-label']) !!}
                    {!! Form::number('section_c_no_of_question', old('section_c_no_of_question'), ['class' => 'form-control', 'placeholder' => 'Enter Section-C Question Quantity']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('section_c_no_of_question'))
                        <p class="help-block">
                            {{ $errors->first('section_c_no_of_question') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('section_c_no_of_point', 'Total Point Of Section-C*', ['class' => 'control-label']) !!}
                    {!! Form::number('section_c_no_of_point', old('section_c_no_of_point'), ['class' => 'form-control', 'placeholder' => 'Enter Section-C Point']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('section_c_no_of_point'))
                        <p class="help-block">
                            {{ $errors->first('section_c_no_of_point') }}
                        </p>
                    @endif
                </div>
            </div>
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/question_level_details/index.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.questionLevel.details')</h3>

    <p>
        <a href="{{ route('questionLevelDetail.create') }}" class="btn btn-success">@lang('quickadmin.add_new')</a>
    </p>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.list')
        </div>
        <div class="panel-body">
            <table class="table table-bordered table-striped {{ count($levelDetails) > 0 ? 'datatable' : '' }}">
                <thead>
                    <tr>
                        <th style="text-align:center;">Sr</th>
                        <th>Level</th>
                        <th>No Of Question Of Section-A</th>
                        <th>Total Point Of Section-A</th>
                        <th>No Of Question Of Section-B</th>
                        <th>Total Point Of Section-B</th>
                        <th>No Of Question Of Section-C</th>
                        <th>Total Point Of Section-C</th>
                        <th>Action</th>
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($levelDetails) > 0)
                        @foreach ($levelDetails as $key => $detail)
                            <tr data-entry-id="{{ $detail->id }}">
                                <td>{{++$key}}</td>
                                <td>{{ $detail->level->title or null }}</td>
                                <td>{{ $detail->section_a_no_of_question or null }}</td>
                                <td>{{ $detail->section_a_no_of_point or null }}</td>
                                <td>{{ $detail->section_b_no_of_question or null }}</td>
                                <td>{{ $detail->section_b_no_of_point or null }}</td>
                                <td>{{ $detail->section_c_no_of_question or null }}</td>
                                <td>{{ $detail->section_c_no_of_point or null }}</td>
                                <td>
                                   {{-- <a href="{{ route('packages.show',[$detail->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.view')</a>--}}
                                    <a href="{{ route('questionLevelDetail.edit',[$detail->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.edit')</a>
                                   {{--{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.are_you_sure")."');",
                                        'route' => ['questionLevelDetail.destroy', $detail->id])) !!}
                                    {!! Form::submit(trans('quickadmin.delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}--}}
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="3">@lang('quickadmin.no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript')
   {{-- <script>
        window.route_mass_crud_entries_destroy = '{{ route('stages.mass_destroy') }}';
    </script>--}}
@endsection

resources/views/question_level_details/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.packages.packages')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.view')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>Name</th>
                            <td>{{ $package->name }}</td>
                        </tr>
                        <tr>
                            <th>Category</th>
                            <td>{{ $package->category->name }}</td>
                        </tr>
                        <tr>
                            <th>Quantity</th>
                            <td>{{ $package->quantity }}</td>
                        </tr>
                        <tr>
                            <th>Price</th>
                            <td>{{ $package->price }}</td>
                        </tr>
                    </table>
                </div>
            </div>

            <p>&nbsp;</p>

            <a href="{{ route('packages.index') }}" class="btn btn-default">@lang('quickadmin.back_to_list')</a>
        </div>
    </div>
@stop