routes/web.php
<?php
Route::get('/', function () {
    return redirect('/home');
});

// Auth::routes();

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');
/*$this->get('oauth2google', 'Auth\Oauth2Controller@oauth2google')->name('oauth2google');
$this->get('googlecallback', 'Auth\Oauth2Controller@googlecallback')->name('googlecallback');
$this->get('oauth2facebook', 'Auth\Oauth2Controller@oauth2facebook')->name('oauth2facebook');
$this->get('facebookcallback', 'Auth\Oauth2Controller@facebookcallback')->name('facebookcallback');
$this->get('oauth2github', 'Auth\Oauth2Controller@oauth2github')->name('oauth2github');
$this->get('githubcallback', 'Auth\Oauth2Controller@githubcallback')->name('githubcallback');*/

// Registration Routes...
/*$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');*/

// Password Reset Routes...
/*$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('auth.password.email');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');*/


Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('tests', 'TestsController');
    Route::resource('roles', 'RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'UsersController');
    Route::post('users_mass_destroy', ['uses' => 'UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'UserActionsController');
    Route::resource('topics', 'TopicsController');
    Route::post('topics_mass_destroy', ['uses' => 'TopicsController@massDestroy', 'as' => 'topics.mass_destroy']);
    Route::resource('questions', 'QuestionsController');
    Route::post('questions_mass_destroy', ['uses' => 'QuestionsController@massDestroy', 'as' => 'questions.mass_destroy']);
    Route::resource('questions_options', 'QuestionsOptionsController');
    Route::post('questions_options_mass_destroy', ['uses' => 'QuestionsOptionsController@massDestroy', 'as' => 'questions_options.mass_destroy']);
    Route::resource('results', 'ResultsController');
    Route::post('results_mass_destroy', ['uses' => 'ResultsController@massDestroy', 'as' => 'results.mass_destroy']);

    //question level
    Route::resource('questionLevel', 'QuestionLevelController');

    //question level details
    Route::resource('questionLevelDetail', 'QuestionLevelDetailController');

    //Manage Package category
    Route::resource('packageCategory', 'PackageCategoryController');
    Route::post('categories_mass_destroy', ['uses' => 'PackageCategoryController@massDestroy', 'as' => 'packageCategory.mass_destroy']);

    //Manage Package
    Route::resource('packages', 'PackageController');

    //Manage Puzzles
    Route::resource('stages', 'StageController');

    //Manage Level
    Route::resource('levels', 'LevelController');

    //patterns
    Route::resource('patterns', 'PatternController');

    //Puzzles
    Route::resource('puzzles', 'PuzzleController');
    Route::post('load-pattern-schema','PatternSchemaController@patternSchema')->name('pattern-schema');
    Route::post('stage-wise-level','ManageDropDownController@levelListDependOnStage')->name('stage-wise-level');

    //Manage User
    Route::resource('app-users','AppUsersController');
    Route::get('push-notification','PushNotificationController@push')->name('push');
    Route::post('send-push','PushNotificationController@sendPush')->name('push.send');

    //settings
    Route::resource('pointSettings','PointSettingController');
});

app/QuestionLevel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class QuestionLevel extends Model
{
    protected $fillable = ['title','level_cost','playable_question','playable_time'];

    public function detail()
    {
       return $this->hasOne(QuestionLevelDetail::class,'question_level_id');
    }
}

app/Http/Controllers/QuestionLevelController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\QuestionLevelRequest;
use App\QuestionLevel;
use Illuminate\Http\Request;

class QuestionLevelController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $levels = QuestionLevel::orderBy('id','desc')->get();
        return view('question_level.index', compact('levels'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('question_level.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(QuestionLevelRequest $request)
    {
        QuestionLevel::create($request->all());
        return redirect()->route('questionLevel.index')->with('message', 'Saved successfully!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\QuestionLevel  $questionLevel
     * @return \Illuminate\Http\Response
     */
    public function show(QuestionLevel $questionLevel)
    {
        return view('question_level.show', compact('questionLevel'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\QuestionLevel  $questionLevel
     * @return \Illuminate\Http\Response
     */
    public function edit(QuestionLevel $questionLevel)
    {
        return view('question_level.edit', compact('questionLevel'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\QuestionLevel  $questionLevel
     * @return \Illuminate\Http\Response
     */
    public function update(QuestionLevelRequest $request, QuestionLevel $questionLevel)
    {
        $questionLevel->update($request->all());
        return redirect()->route('questionLevel.index')->with('message', 'Saved successfully!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\QuestionLevel  $questionLevel
     * @return \Illuminate\Http\Response
     */
    public function destroy(QuestionLevel $questionLevel)
    {
        $questionLevel->forceDelete();
        return redirect()->route('questionLevel.index')->with('message', 'Delete successfully!!');
    }
}

resources/views/question_level/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.questionLevel.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['questionLevel.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.create')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-6 form-group">
                    {!! Form::label('title', 'Title*', ['class' => 'control-label']) !!}
                    {!! Form::text('title', old('title'), ['class' => 'form-control', 'placeholder' => 'Enter Title']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('title'))
                        <p class="help-block">
                            {{ $errors->first('title') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('level_cost', 'Level Cost*', ['class' => 'control-label']) !!}
                    {!! Form::text('level_cost', old('level_cost'), ['class' => 'form-control', 'placeholder' => 'Enter Title']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('level_cost'))
                        <p class="help-block">
                            {{ $errors->first('level_cost') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6 form-group">
                    {!! Form::label('playable_question', 'No Of Playable Question*', ['class' => 'control-label']) !!}
                    {!! Form::number('playable_question', old('playable_question'), ['class' => 'form-control', 'placeholder' => 'Enter Playable Question Quantity']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('playable_question'))
                        <p class="help-block">
                            {{ $errors->first('playable_question') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('playable_time', 'Total Playable Time*', ['class' => 'control-label']) !!}
                    {!! Form::number('playable_time', old('playable_time'), ['class' => 'form-control', 'placeholder' => 'Enter Playable Time']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('playable_time'))
                        <p class="help-block">
                            {{ $errors->first('playable_time') }}
                        </p>
                    @endif
                </div>
            </div>
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop
{{--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="{{asset('quickadmin/js/moment.min.js')}}"></script>
<script src="{{asset('quickadmin/js/bootstrap-datetimepicker.js')}}"></script>
<script src="{{asset('quickadmin/js/bootstrap-timepicker.js')}}"></script>
<script type="text/javascript">
    $(function () {
        $('.time').datetimepicker({
            format: 'LT'
        });
    });
</script>--}}

resources/views/question_level/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.questionLevel.details')</h3>
    
    {!! Form::model($questionLevel, ['method' => 'PUT', 'route' => ['questionLevel.update', $questionLevel->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-6 form-group">
                    {!! Form::label('title', 'Title*', ['class' => 'control-label']) !!}
                    {!! Form::text('title', old('title'), ['class' => 'form-control', 'placeholder' => 'Enter Title']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('title'))
                        <p class="help-block">
                            {{ $errors->first('title') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('level_cost', 'Level Cost*', ['class' => 'control-label']) !!}
                    {!! Form::text('level_cost', old('level_cost'), ['class' => 'form-control', 'placeholder' => 'Enter Title']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('level_cost'))
                        <p class="help-block">
                            {{ $errors->first('level_cost') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6 form-group">
                    {!! Form::label('playable_question', 'No Of Playable Question*', ['class' => 'control-label']) !!}
                    {!! Form::number('playable_question', old('playable_question'), ['class' => 'form-control', 'placeholder' => 'Enter Playable Question Quantity']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('playable_question'))
                        <p class="help-block">
                            {{ $errors->first('playable_question') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('playable_time', 'Total Playable Time*', ['class' => 'control-label']) !!}
                    {!! Form::number('playable_time', old('playable_time'), ['class' => 'form-control', 'placeholder' => 'Enter Playable Time']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('playable_time'))
                        <p class="help-block">
                            {{ $errors->first('playable_time') }}
                        </p>
                    @endif
                </div>
            </div>
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/question_level/index.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.questionLevel.title')</h3>

    <p>
        <a href="{{ route('questionLevel.create') }}" class="btn btn-success">@lang('quickadmin.add_new')</a>
    </p>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.list')
        </div>
        <div class="panel-body">
            <table class="table table-bordered table-striped {{ count($levels) > 0 ? 'datatable' : '' }}">
                <thead>
                    <tr>
                        <th style="text-align:center;">Sr</th>
                        <th>Title</th>
                        <th>No Of Playable Question</th>
                        <th>Total Playable Time</th>
                        <th class="text-center">Level Cost</th>
                        <th>Action</th>
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($levels) > 0)
                        @foreach ($levels as $key => $level)
                            <tr>
                                <td>{{++$key}}</td>
                                <td>{{ $level->title or null}}</td>
                                <td>{{ $level->playable_question or null}}</td>
                                <td>{{ $level->playable_time or null }}</td>
                                <td class="success text-center">{{ $level->level_cost or null }}</td>
                                <td>
                                   {{-- <a href="{{ route('questionLevel.show',[$level->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.view')</a>--}}
                                    <a href="{{ route('questionLevel.edit',[$level->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.edit')</a>
                                  {{-- {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.are_you_sure")."');",
                                        'route' => ['questionLevel.destroy', $level->id])) !!}
                                    {!! Form::submit(trans('quickadmin.delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}--}}
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="3">@lang('quickadmin.no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript')
   {{-- <script>
        window.route_mass_crud_entries_destroy = '{{ route('stages.mass_destroy') }}';
    </script>--}}
@endsection

resources/views/question_level/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.packages.packages')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.view')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>Name</th>
                            <td>{{ $package->name }}</td>
                        </tr>
                        <tr>
                            <th>Category</th>
                            <td>{{ $package->category->name }}</td>
                        </tr>
                        <tr>
                            <th>Quantity</th>
                            <td>{{ $package->quantity }}</td>
                        </tr>
                        <tr>
                            <th>Price</th>
                            <td>{{ $package->price }}</td>
                        </tr>
                    </table>
                </div>
            </div>

            <p>&nbsp;</p>

            <a href="{{ route('packages.index') }}" class="btn btn-default">@lang('quickadmin.back_to_list')</a>
        </div>
    </div>
@stop