routes/web.php
<?php
Route::get('/', function () {
    return redirect('/home');
});

// Auth::routes();

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');
/*$this->get('oauth2google', 'Auth\Oauth2Controller@oauth2google')->name('oauth2google');
$this->get('googlecallback', 'Auth\Oauth2Controller@googlecallback')->name('googlecallback');
$this->get('oauth2facebook', 'Auth\Oauth2Controller@oauth2facebook')->name('oauth2facebook');
$this->get('facebookcallback', 'Auth\Oauth2Controller@facebookcallback')->name('facebookcallback');
$this->get('oauth2github', 'Auth\Oauth2Controller@oauth2github')->name('oauth2github');
$this->get('githubcallback', 'Auth\Oauth2Controller@githubcallback')->name('githubcallback');*/

// Registration Routes...
/*$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');*/

// Password Reset Routes...
/*$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('auth.password.email');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');*/


Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('tests', 'TestsController');
    Route::resource('roles', 'RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'UsersController');
    Route::post('users_mass_destroy', ['uses' => 'UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'UserActionsController');
    Route::resource('topics', 'TopicsController');
    Route::post('topics_mass_destroy', ['uses' => 'TopicsController@massDestroy', 'as' => 'topics.mass_destroy']);
    Route::resource('questions', 'QuestionsController');
    Route::post('questions_mass_destroy', ['uses' => 'QuestionsController@massDestroy', 'as' => 'questions.mass_destroy']);
    Route::resource('questions_options', 'QuestionsOptionsController');
    Route::post('questions_options_mass_destroy', ['uses' => 'QuestionsOptionsController@massDestroy', 'as' => 'questions_options.mass_destroy']);
    Route::resource('results', 'ResultsController');
    Route::post('results_mass_destroy', ['uses' => 'ResultsController@massDestroy', 'as' => 'results.mass_destroy']);

    //question level
    Route::resource('questionLevel', 'QuestionLevelController');

    //question level details
    Route::resource('questionLevelDetail', 'QuestionLevelDetailController');

    //Manage Package category
    Route::resource('packageCategory', 'PackageCategoryController');
    Route::post('categories_mass_destroy', ['uses' => 'PackageCategoryController@massDestroy', 'as' => 'packageCategory.mass_destroy']);

    //Manage Package
    Route::resource('packages', 'PackageController');

    //Manage Puzzles
    Route::resource('stages', 'StageController');

    //Manage Level
    Route::resource('levels', 'LevelController');

    //patterns
    Route::resource('patterns', 'PatternController');

    //Puzzles
    Route::resource('puzzles', 'PuzzleController');
    Route::post('load-pattern-schema','PatternSchemaController@patternSchema')->name('pattern-schema');
    Route::post('stage-wise-level','ManageDropDownController@levelListDependOnStage')->name('stage-wise-level');

    //Manage User
    Route::resource('app-users','AppUsersController');
    Route::get('push-notification','PushNotificationController@push')->name('push');
    Route::post('send-push','PushNotificationController@sendPush')->name('push.send');

    //settings
    Route::resource('pointSettings','PointSettingController');
});

app/AppUser.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class AppUser extends Model
{
    use SoftDeletes;
    //protected $appends = ['profile_image'];
    protected $fillable = ['name','phone_no','profile_image', 'status','points','life','help','page_qty','refer_points','refer_code','point_setting_id','app_token'];
    protected $hidden = ['pivot'];

    public function coins()
    {
        return $this->hasMany(Coin::class,'app_user_id');
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class,'app_user_id');
    }

    public function puzzles()
    {
        return $this->belongsToMany(Puzzle::class, 'app_user_puzzle', 'app_user_id', 'puzzle_id');
    }

    public function puzzleSummery()
    {
        return $this->hasMany(AppUserPuzzleSummery::class,'app_user_id');
    }

    public function getProfileImageAttribute($value)
    {
        return !empty($value) ? "http://192.168.10.101:800/right_bell/public/$value" : '';
    }

    public function pointCategory()
    {
        return $this->belongsTo(PointSetting::class,'point_setting_id','id');
    }
}

app/Http/Controllers/AppUsersController.php
<?php

namespace App\Http\Controllers;

use App\AppUser;
use Illuminate\Http\Request;

class AppUsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $appUsers = AppUser::orderBy('id', 'desc')->get();
        return view('app_users.index', compact('appUsers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\AppUser  $appUser
     * @return \Illuminate\Http\Response
     */
    public function show(AppUser $appUser)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\AppUser  $appUser
     * @return \Illuminate\Http\Response
     */
    public function edit(AppUser $appUser)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\AppUser  $appUser
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, AppUser $appUser)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\AppUser  $appUser
     * @return \Illuminate\Http\Response
     */
    public function destroy(AppUser $appUser)
    {
        //
    }
}

resources/views/app_users/index.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.app_users.users')</h3>

    {{--  <p>
          <a href="{{ route('users.create') }}" class="btn btn-success">@lang('quickadmin.add_new')</a>
      </p>--}}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.list')
        </div>

        <div class="panel-body">
            <table class="table table-bordered table-striped {{ count($appUsers) > 0 ? 'datatable' : '' }}">
                <thead>
                <tr>
                    <th style="text-align:center;">Sr</th>
                    <th>Name</th>
                    <th>Phone No</th>
                    <th>Refer Code</th>
                    <th>Refer Point</th>
                    <th>Page Qty</th>
                    <th>Life</th>
                    <th>Help</th>
                    <th>Point</th>
                    <th>Image</th>
                </tr>
                </thead>

                <tbody>
                @if (count($appUsers) > 0)
                    @foreach ($appUsers as $key => $user)
                        <tr data-entry-id="{{ $user->id }}">
                            <td>{{++$key}}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->phone_no }}</td>
                            <td class="text-center"><span class="label label-success">{{ $user->refer_code }}</span></td>
                            <td>{{ $user->refer_points }}</td>
                            <td>{{ $user->page_qty }}</td>
                            <td>{{ $user->life }}</td>
                            <td>{{ $user->help }}</td>
                            <td>{{ $user->points }}</td>
                            <td>
                                @if(!empty($user->profile_image))
                                    <img style="border-radius: 50% !important;" src="{{asset($user->profile_image)}}" width="65px" height="65px" alt="Profile Image">
                                @else
                                    <img src="{{asset("default/user.png")}}" alt="Profile Image">
                                @endif
                            </td>
                            {{--  <td>
                                  <a href="{{ route('users.show',[$user->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.view')</a>
                                  <a href="{{ route('users.edit',[$user->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.edit')</a>
                                  {!! Form::open(array(
                                      'style' => 'display: inline-block;',
                                      'method' => 'DELETE',
                                      'onsubmit' => "return confirm('".trans("quickadmin.are_you_sure")."');",
                                      'route' => ['users.destroy', $user->id])) !!}
                                  {!! Form::submit(trans('quickadmin.delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                  {!! Form::close() !!}
                              </td>--}}
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="7">@lang('quickadmin.no_entries_in_table')</td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript')
    {{-- <script>
         window.route_mass_crud_entries_destroy = '{{ route('users.mass_destroy') }}';
     </script>--}}
@endsection